import type { Config } from "tailwindcss";
import twAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  theme: {
    extend: {
      zIndex: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "20": "20",
        "30": "30",
        "40": "40",
        "50": "50",
        "60": "60",
        "70": "70",
        "80": "80",
        "90": "90",
        "100": "100",
      },
      scale: {
        "200": "2.0",
        "250": "2.5",
        "300": "3.0",
        "350": "3.5",
        "400": "4.0",
        "450": "4.5",
        "500": "5.0",
        "550": "5.5",
      },
      spacing: {
        "1%": "1%",
        "2%": "2%",
        "3%": "3%",
        "4%": "4%",
        "5%": "5%",
        "6%": "6%",
        "7%": "7%",
        "8%": "8%",
        "9%": "9%",
        "10%": "10%",
        "15%": "15%",
        "20%": "20%",
        "25%": "25%",
        "30%": "30%",
        "35%": "35%",
        "40%": "40%",
        "45%": "45%",
        "50%": "50%",
      },
      fontFamily: {
        cavet: ["Cavet", "cursive"],
        anton: ["Anton", "sans-serif"],
        titillium: ["TitilliumWeb", "sans-serif"],
        inter: ["var(--font-sans)", "sans-serif"],
      },
      gridTemplateColumns: {
        "fit-8": "repeat(auto-fit, minmax(8em, 1fr))",
        "fit-10": "repeat(auto-fit, minmax(10em, 1fr))",
        "fit-12": "repeat(auto-fit, minmax(12em, 1fr))",
        "fit-14": "repeat(auto-fit, minmax(14em, 1fr))",
        "fit-16": "repeat(auto-fit, minmax(16em, 1fr))",
        "fit-18": "repeat(auto-fit, minmax(18em, 1fr))",
        "fit-20": "repeat(auto-fit, minmax(20em, 1fr))",
        "fit-22": "repeat(auto-fit, minmax(22em, 1fr))",
        "fit-24": "repeat(auto-fit, minmax(24em, 1fr))",
        "fill-8": "repeat(auto-fill, minmax(8em, 1fr))",
        "fill-10": "repeat(auto-fill, minmax(10em, 1fr))",
        "fill-12": "repeat(auto-fill, minmax(12em, 1fr))",
        "fill-14": "repeat(auto-fill, minmax(14em, 1fr))",
        "fill-16": "repeat(auto-fill, minmax(16em, 1fr))",
        "fill-18": "repeat(auto-fill, minmax(18em, 1fr))",
        "fill-20": "repeat(auto-fill, minmax(20em, 1fr))",
        "fill-22": "repeat(auto-fill, minmax(22em, 1fr))",
        "fill-24": "repeat(auto-fill, minmax(24em, 1fr))",
      },
      backgroundImage: {
        logo: "url('/LOGOJ2.png')",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        dark: "hsl(var(--dark))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
    },
  },
  plugins: [twAnimate],
  content: ["./src/**/**/*.{js,ts,jsx,tsx,mdx}"],
} satisfies Config;
